### ISSUE TITLE
Omit null values from int, float and maybe other types of Tableau columns

### ISSUE THREAD

**Issue by aarenson** [lsgs/redcap-tableau-wdc#10]
According to this Tableau forum post: (https://community.tableau.com/message/606568#606568)

The way to get null values into int, float, and maybe other types is to omit the field. Otherwise, the null will be converted to the default value of that type.

 I _think_ the omission of fields would need to occur in the 'success' anonymous callback function in the ajax call that gets the record data. Right now it looks like:

> resp.forEach(function(record) {
>      tableData.push(record);
> });
> ...

I'd guess something needs to occur before that push to pull the null values out of the record.

**Comment by lsgs** [comment]
Release 2.2.3.
Much appreciated @aarenson
