### ISSUE TITLE
Tableau public error Web data connector

### ISSUE THREAD

**Issue by MathiasAntunes** [lsgs/redcap-tableau-wdc#13]
Hi luke !
Thank you for the WDC !
I'm testing the connector between REDCap 8.10.2 and Tableau Public 2019.3.0.
Tableau returns the following error :
`
An error occurred while communicating with the data source.
The web data connector returned invalid data.
Either invalid data are present or required fields are empty for class TableInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true),
(Name : 'columns', Type : QVariantList, IsRequired : true),
(Name : 'alias', Type : QString, IsRequired : false),
(Name : 'description', Type : QString, IsRequired : false),
(Name : 'incrementColumnId', Type : QString, IsRequired : false),
(Name : 'joinOnly', Type : bool, IsRequired : false)
}
`

Thank you.

**Comment by lsgs** [comment]
Is this still a problem for you @MathiasAntunes ? I can't replicate it in my more recent versions of REDCap and Tableau.
