### ISSUE TITLE
js error when submitting

### ISSUE THREAD

**Issue by jthomas08** [lsgs/redcap-tableau-wdc#16]
Luke,
I get the following in my desktop tableu logs when submitting the token and other config:
edu/api/?type=module&prefix=redcap-tableau-wdc&page=wdc&NOAUTH:**450 -- TypeError: tableau.submit is not a function"}**

I'm using FF on redcap 9.5.x, Tableau Desktop 2020.2.0,

**Comment by lsgs** [comment]
Can you go to the module settings in your Control Center and tell it to use a more up-to-date version of the Tableau code? I'm using https://connectors.tableau.com/libs/tableauwdc-2.3.latest.js

See this issue: https://github.com/lsgs/redcap-tableau-wdc/issues/15
