### ISSUE TITLE
Submit Button Not Working (on latest.js version)

### ISSUE THREAD

**Issue by BrandonHallChildrens** [lsgs/redcap-tableau-wdc#19]
We just installed the EM, which looks like it has the latest.js update, but the submit button is still not working. I attempted to use the Chromium debugger, but there was no response in the sources for any calls being made. Was able to get it working in the Tableau WDC simulator, but not in Tableau itself. I saw in the code that there was a workaround added due to this, but I'm still stuck on the Submit button not doing anything. Is anyone using the WDC with the latest Tableau versions, or does anyone have something they have done to get it working?

REDCap version 11.1.17
Tableau Desktop version 2021.4

**Comment by lsgs** [comment]
Hello @BrandonHallChildrens. Can you upgrade past 11.2.0? I can't really justify any time supporting this functionality as a module now that it is a core feature of REDCap.
