### ISSUE TITLE
Project not installed

### ISSUE THREAD

**Issue by schulickn** [lsgs/redcap-tableau-wdc#21]
For organizations that self-host, the external modules are not already installed into our REDCap server, therefore we can't follow instructions starting at #1"enable the module" because it does not appear for us.

Please include instructions on how to install the module onto our server?
Thanks.

**Comment by lsgs** [comment]
The functionality of this Tableau WDC external module was incorporated within core functinality as of REDCap v11.2.0 (released 09-Jul-2023). Look for it under "Other Export Options" on the Data Exports page. The EM is no longer supported.
