### ISSUE TITLE
Native Tableau WDC

### ISSUE THREAD

**Issue by carsonk3** [lsgs/redcap-tableau-wdc#5]
I’ve just gotten off the phone with Tableau tech support. They don’t generally have support for “non-native connectors”. This makes it so they have limited levels of support and support can take a lot of time. Your WDC has been super helpful, but it would be amazing if Tableau could incorporate it into their native connectors. Tech support says they didn't know there was a need/desire for a WDC because no one added it to the idea board/upvoted it. I just added it. If you could upvote it, that would be super helpful. 

Here’s the link: https://community.tableau.com/ideas/9073 

I thought posting this in the "issues" section might make it so other can see/vote as well. Thanks!

**Comment by lsgs** [comment]
Good idea @carsonk3. I've added my vote to your request. Glad you're finding this EM useful in the meantime. Thanks.
