### ISSUE TITLE
Warning about non-compound name in use statement

### ISSUE THREAD

**Issue by aarenson** [lsgs/redcap-tableau-wdc#9]
Warning: The use statement with non-compound name 'HtmlPage' has no effect in /var/www/vhosts/redcap.uits.iu.edu/modules/tableau_connector_v2.2.1/wdc.php on line 7

The above warning shows up at the top of the pop up window where one would enter API token, raw data or labels?, etc.

It is occurring when I test out WDC 2.2.1 from our staging server, but is not occurring in WDC 2.2.0 on our production server.  Both servers are using REDCap 8.10.10 and PHP 7.1.24.

**Comment by aarenson** [comment]
I see no changes in the code that would lead to this discrepancy, so my guess is that the difference is related to some sort of discrepancy between our servers, but I don't know what it would be.

**Comment by aarenson** [comment]
Weirdly, this doesn't appear to be a repeatable error! I can't get the warning to show up again.

**Comment by aarenson** [comment]
This error showed up again. I haven't been able to pin down why it only sometimes occurs.

The use statement can probably simple be removed.

I'm working on a change to set some Tableau columns to be numbers rather than strings, and I've commented out the use statement and everything continues to work.

**Comment by lsgs** [comment]
Much appreciated @aarenson!
